services:
  app:
    build: . # Constrói a imagem usando o Dockerfile no diretório atual
    container_name: node-app
    restart: unless-stopped
    ports:
      - "80:3000" # Porta 80 do host redirecionada para 3000 no container
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST:-db}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
      - DB_NAME=${DB_NAME:-mydatabase}
      - DB_PORT=${DB_PORT:-3306}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_DATABASE=${DB_NAME:-mydatabase}
      - MYSQL_USER=${DB_USER:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
    volumes:
      - ./.db-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306" # Descomente se precisar acesso externo

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
