-- CreateTable
CREATE TABLE `deals` (
    `id` INTEGER NOT NULL,
    `title` VARCHAR(191) NULL,
    `creator_user_id` INTEGER NULL,
    `owner_id` INTEGER NULL,
    `pipeline` INTEGER NULL,
    `stage_id` INTEGER NULL,
    `status` VARCHAR(191) NULL,
    `add_time` DATETIME(3) NULL,
    `update_time` DATETIME(3) NULL,
    `stage_change_time` DATETIME(3) NULL,
    `next_activity_date` DATETIME(3) NULL,
    `last_activity_date` DATETIME(3) NULL,
    `won_time` DATETIME(3) NULL,
    `lost_time` DATETIME(3) NULL,
    `close_time` DATETIME(3) NULL,
    `lost_reason` VARCHAR(191) NULL,
    `visible_to` VARCHAR(191) NULL,
    `activities_count` INTEGER NULL,
    `done_activities_count` INTEGER NULL,
    `undone_activities_count` INTEGER NULL,
    `email_messages_count` INTEGER NULL,
    `value` DECIMAL(12, 2) NULL,
    `currency` VARCHAR(191) NULL,
    `org_id` INTEGER NULL,
    `person_id` INTEGER NULL,
    `expected_close_date` DATETIME(3) NULL,
    `probability` INTEGER NULL,
    `label` VARCHAR(191) NULL,
    `weighted_value` DECIMAL(12, 2) NULL,
    `weighted_value_currency` VARCHAR(191) NULL,
    `origin` VARCHAR(191) NULL,
    `origin_id` VARCHAR(191) NULL,
    `channel_id` VARCHAR(191) NULL,
    `is_archived` BOOLEAN NULL,
    `archive_time` DATETIME(3) NULL,
    `tipos_de_processos` VARCHAR(191) NULL,
    `link_proposta` VARCHAR(191) NULL,
    `link_pre_busca_it` VARCHAR(191) NULL,
    `resultado_pre_busca` VARCHAR(191) NULL,
    `link_pre_busca_br` VARCHAR(191) NULL,
    `link_guru` VARCHAR(191) NULL,
    `type_parente_portugues` VARCHAR(191) NULL,
    `type_docs_portugues` VARCHAR(191) NULL,
    `type_outros_familiares` VARCHAR(191) NULL,
    `type_visitou_portugal` VARCHAR(191) NULL,
    `type_objetivo` VARCHAR(191) NULL,
    `loja_sdr` VARCHAR(191) NULL,
    `loja_inside` VARCHAR(191) NULL,
    `sdr_passagem_sdr` VARCHAR(191) NULL,
    `sdr_data_passagem` DATETIME(3) NULL,
    `sdr_quem_passou_id` INTEGER NULL,
    `sdr_original_id` INTEGER NULL,
    `tipo_de_venda` VARCHAR(191) NULL,
    `data_retorno` DATETIME(3) NULL,
    `valor_total_processo_automacao` VARCHAR(191) NULL,
    `forma_pagamento_automacao` TEXT NULL,
    `processos_fechados_automacao` TEXT NULL,
    `infos_pt_automacao` TEXT NULL,
    `tipo_certidao_pt_automacao` VARCHAR(191) NULL,
    `versao_precificacao_automacao` VARCHAR(191) NULL,
    `indicacao` VARCHAR(191) NULL,
    `certidao_portugues` VARCHAR(191) NULL,
    `cf_nome` VARCHAR(191) NULL,
    `cf_telefone` VARCHAR(191) NULL,
    `numero_assento` VARCHAR(191) NULL,
    `numero_processo_portugal` VARCHAR(191) NULL,
    `sao_menores_idade` VARCHAR(191) NULL,
    `nome_completo_portugues` VARCHAR(191) NULL,
    `nome_completo_mae_portugues` VARCHAR(191) NULL,
    `nome_completo_pai_portugues` VARCHAR(191) NULL,
    `concelho_nascimento_portuga` VARCHAR(191) NULL,
    `numero_rastreamento` VARCHAR(191) NULL,
    `valor_certidao` VARCHAR(191) NULL,
    `nome_completo_contratante` VARCHAR(191) NULL,
    `cpf_contratante` VARCHAR(191) NULL,
    `rg_contratante` VARCHAR(191) NULL,
    `orgao_emissor_rg_contratante` VARCHAR(191) NULL,
    `data_emissao_rg_contratante` VARCHAR(191) NULL,
    `cep_contratante` VARCHAR(191) NULL,
    `endereco_contratante` VARCHAR(191) NULL,
    `assento_ascendente_portuga` VARCHAR(191) NULL,
    `possui_plano_familia` VARCHAR(191) NULL,
    `codigo_produto` TEXT NULL,
    `docs_emission` VARCHAR(191) NULL,
    `processos_fechados_mika_automacao` TEXT NULL,
    `docs_anexados_produto` TEXT NULL,
    `parente_italiano` VARCHAR(191) NULL,
    `local_nascimento_italiano` VARCHAR(191) NULL,
    `compromisso_inicial` VARCHAR(191) NULL,
    `vendedor_original` VARCHAR(191) NULL,
    `docs_italiano` VARCHAR(191) NULL,
    `data_recebido` DATETIME(3) NULL,
    `historico_proprietario` TEXT NULL,
    `status_negocio_andamento` VARCHAR(191) NULL,
    `sdr_passagem_resposta` VARCHAR(191) NULL,
    `it_chatbot` VARCHAR(191) NULL,
    `it_teste_chatbot` VARCHAR(191) NULL,
    `gclid` TEXT NULL,
    `sdr_intermediario_id` INTEGER NULL,
    `it_chatbot_modelo_msg_inicial` VARCHAR(191) NULL,
    `status_reuniao_chatbot` VARCHAR(191) NULL,
    `criador_shopping_id` INTEGER NULL,
    `resultado_roleta` VARCHAR(191) NULL,
    `resultado_roleta_manual` VARCHAR(191) NULL,
    `data_alocacao` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `deals_owner_id_idx`(`owner_id`),
    INDEX `deals_org_id_idx`(`org_id`),
    INDEX `deals_person_id_idx`(`person_id`),
    INDEX `deals_status_idx`(`status`),
    INDEX `deals_stage_id_idx`(`stage_id`),
    INDEX `deals_pipeline_idx`(`pipeline`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
